# Generated by Django 5.0.6 on 2024-08-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_digidexuser_options_digidexuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digidexuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
