# Generated by Django 5.1 on 2024-10-08 09:03

import django.core.validators
import django.db.models.deletion
import ntags
import ntags.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True, validators=[ntags.validators.validate_ascii_mirror_uid])),
                ('integrated_circuit', models.CharField(choices=[('213', 'NTAG 213'), ('215', 'NTAG 215'), ('216', 'NTAG 216')], default='213', max_length=5)),
                ('label', models.CharField(blank=True, max_length=64, null=True)),
                ('active', models.BooleanField(default=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=ntags.get_nfc_taggable_models, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ntags', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ntags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ntag',
                'verbose_name_plural': 'ntags',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFCTagMemory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('eeprom', models.BinaryField(max_length=924)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('ntag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eeprom', to='ntags.nfctag')),
            ],
            options={
                'verbose_name': 'eeprom',
                'verbose_name_plural': 'eeproms',
            },
        ),
        migrations.CreateModel(
            name='NFCTagScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ntag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='ntags.nfctag')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scan',
                'verbose_name_plural': 'scans',
            },
        ),
        migrations.AddIndex(
            model_name='nfctag',
            index=models.Index(fields=['content_type', 'object_id'], name='ntags_nfcta_content_df13eb_idx'),
        ),
    ]
