# Generated by Django 5.1 on 2024-09-23 18:28

import django.core.validators
import django.db.models.deletion
import ntags.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True, validators=[ntags.validators.validate_serial_number])),
                ('integrated_circuit', models.CharField(choices=[('213', 'NTAG 213'), ('215', 'NTAG 215'), ('216', 'NTAG 216')], default='213', max_length=5, validators=[ntags.validators.validate_integrated_circuit])),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ntags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ntag',
                'verbose_name_plural': 'ntags',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFCTagMemory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('eeprom', models.BinaryField(max_length=888)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('ntag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eeprom', to='ntags.nfctag')),
            ],
            options={
                'verbose_name': 'eeprom',
                'verbose_name_plural': 'eeproms',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFCTagScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ntag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='ntags.nfctag')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scan',
                'verbose_name_plural': 'scans',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFCTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_tagged_items', to='contenttypes.contenttype')),
                ('nfc_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='ntags.nfctag')),
            ],
            options={
                'verbose_name': 'NFC Tagged Item',
                'verbose_name_plural': 'NFC Tagged Items',
                'unique_together': {('nfc_tag', 'content_type', 'object_id')},
            },
        ),
    ]
