# Generated by Django 5.1 on 2024-09-24 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ntags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctagmemory',
            name='ntag',
        ),
        migrations.RemoveField(
            model_name='nfctagscan',
            name='ntag',
        ),
        migrations.RemoveField(
            model_name='nfctagscan',
            name='scanned_by',
        ),
        migrations.CreateModel(
            name='NFCTagLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_tag_links', to='contenttypes.contenttype')),
                ('nfc_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_links', to='ntags.nfctag')),
            ],
            options={
                'verbose_name': 'NFC Tagged Item',
                'verbose_name_plural': 'NFC Tagged Items',
            },
        ),
        migrations.DeleteModel(
            name='NFCTaggedItem',
        ),
        migrations.DeleteModel(
            name='NFCTagMemory',
        ),
        migrations.DeleteModel(
            name='NFCTagScan',
        ),
        migrations.AddIndex(
            model_name='nfctaglink',
            index=models.Index(fields=['content_type', 'object_id'], name='ntags_nfcta_content_05d38c_idx'),
        ),
    ]
