# Generated by Django 5.1 on 2024-10-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctagmemory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='nfctagmemory',
            name='last_modified',
        ),
    ]
