# Generated by Django 5.1 on 2024-09-19 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ntags', '0002_nfctagmemory_expire_at_nfctagmemory_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctag',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'accounts'), ('model', 'User')), models.Q(('app_label', 'botany'), ('model', 'Plant')), models.Q(('app_label', 'inventory'), ('model', 'Box')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
