# Generated by Django 5.1 on 2024-09-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0002_remove_nfctagmemory_ntag_remove_nfctagscan_ntag_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NFCTagLink',
        ),
    ]
