# Generated by Django 5.1 on 2024-10-15 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0002_remove_nfctagmemory_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nfctagscan',
            constraint=models.UniqueConstraint(fields=('ntag', 'counter'), name='unique_ntag_counter'),
        ),
    ]
