# Generated by Django 5.1 on 2024-09-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0003_alter_nfctag_content_type'),
    ]

    operations = [
        migrations.RenameModel('NFCTagMemory', 'NFCTagEEPROM'),
    ]
