# Generated by Django 5.1 on 2024-09-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0004_nfctagmemory_nfctagscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfctag',
            name='label',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
