# Generated by Django 5.1 on 2024-10-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0004_nfctagdesign_nfctag_design_nfctagdesigngalleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfctagdesign',
            options={'ordering': ['name'], 'verbose_name': 'ntag design', 'verbose_name_plural': 'ntag designs'},
        ),
    ]
