# Generated by Django 5.1 on 2024-09-19 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0004_rename_nfctagmemory_to_nfctageeprom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfctageeprom',
            options={'verbose_name': 'ntag eeprom', 'verbose_name_plural': 'ntag eeprom'},
        ),
        migrations.RenameField(
            model_name='nfctageeprom',
            old_name='memory',
            new_name='eeprom',
        ),
        migrations.AlterField(
            model_name='nfctageeprom',
            name='ntag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eeprom', to='ntags.nfctag'),
        ),
    ]
