# Generated by Django 5.1 on 2024-09-20 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0005_alter_nfctageeprom_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfctagdesign',
            options={'verbose_name': 'design', 'verbose_name_plural': 'designs'},
        ),
        migrations.AlterModelOptions(
            name='nfctageeprom',
            options={'verbose_name': 'eeprom', 'verbose_name_plural': 'eeproms'},
        ),
        migrations.AlterModelOptions(
            name='nfctagscan',
            options={'verbose_name': 'scan', 'verbose_name_plural': 'cans'},
        ),
        migrations.RemoveField(
            model_name='nfctag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='nfctag',
            name='label',
        ),
        migrations.RemoveField(
            model_name='nfctag',
            name='object_id',
        ),
        migrations.AddField(
            model_name='nfctag',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ntags', to='ntags.nfctagdesign'),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ntags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nfctagdesign',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nfctagscan',
            name='scanned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
