# Generated by Django 5.1 on 2024-10-16 01:57

import django.db.models.deletion
import ntags
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ntags', '0005_alter_nfctagdesign_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfctag',
            options={'verbose_name': 'nfc-tag', 'verbose_name_plural': 'nfc-tags'},
        ),
        migrations.AlterModelOptions(
            name='nfctagdesign',
            options={'ordering': ['name'], 'verbose_name': 'nfc_tag design', 'verbose_name_plural': 'nfc_tag designs'},
        ),
        migrations.RemoveConstraint(
            model_name='nfctagscan',
            name='unique_ntag_counter',
        ),
        migrations.RenameField(
            model_name='nfctagmemory',
            old_name='ntag',
            new_name='nfc_tag',
        ),
        migrations.RenameField(
            model_name='nfctagscan',
            old_name='ntag',
            new_name='nfc_tag',
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=ntags.get_nfc_taggable_models, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_tags', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ntags.nfctagdesign'),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nfctagdesign',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_tag_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='nfctagscan',
            constraint=models.UniqueConstraint(fields=('nfc_tag', 'counter'), name='unique_nfc_tag_counter'),
        ),
    ]
