# Generated by Django 5.1 on 2024-09-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0006_alter_nfctagdesign_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfctagscan',
            options={'verbose_name': 'scan', 'verbose_name_plural': 'scans'},
        ),
        migrations.RemoveField(
            model_name='nfctagdesign',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='nfctageeprom',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='nfctageeprom',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='nfctageeprom',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='nfctageeprom',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='nfctageeprom',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='nfctageeprom',
            name='integrated_circuit',
        ),
        migrations.RemoveField(
            model_name='nfctageeprom',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='nfctageeprom',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='nfctageeprom',
            name='live',
        ),
        migrations.RemoveField(
            model_name='nfctageeprom',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='nfctageeprom',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='nfctageeprom',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='nfctageeprom',
            name='locked_by',
        ),
        migrations.AddField(
            model_name='nfctag',
            name='integrated_circuit',
            field=models.CharField(choices=[('213', 'NTAG 213'), ('215', 'NTAG 215'), ('216', 'NTAG 216')], default='213', max_length=5),
        ),
    ]
