# Generated by Django 5.1 on 2024-10-16 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ntags', '0006_alter_nfctag_options_alter_nfctagdesign_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='Content type')),
                ('nfc_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='ntags.nfctag')),
            ],
            options={
                'verbose_name': 'NFC Tagged Item',
                'verbose_name_plural': 'NFC Tagged Items',
                'unique_together': {('content_type', 'object_id', 'nfc_tag')},
            },
        ),
    ]
