# Generated by Django 5.1 on 2024-09-28 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ntags', '0006_nfctag_content_type_nfctag_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctag',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ntags', to='contenttypes.contenttype'),
        ),
    ]
