# Generated by Django 5.1 on 2024-09-20 16:56

import ntags.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0007_alter_nfctagscan_options_remove_nfctagdesign_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctag',
            name='integrated_circuit',
            field=models.CharField(choices=[('213', 'NTAG 213'), ('215', 'NTAG 215'), ('216', 'NTAG 216')], default='213', max_length=5, validators=[ntags.validators.validate_integrated_circuit]),
        ),
    ]
