# Generated by Django 5.1 on 2024-10-16 03:31

import django.db.models.deletion
import ntags
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ntags', '0007_nfctaggeditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctagmemory',
            name='nfc_tag',
        ),
        migrations.AlterModelOptions(
            name='nfctag',
            options={'ordering': ['serial_number'], 'verbose_name': 'nfc-tag', 'verbose_name_plural': 'nfc-tags'},
        ),
        migrations.RemoveIndex(
            model_name='nfctag',
            name='ntags_nfcta_content_df13eb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='nfctaggeditem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='nfctag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='nfctag',
            name='object_id',
        ),
        migrations.AddField(
            model_name='nfctag',
            name='eeprom',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='label',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='nfctaggeditem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=ntags.get_nfc_taggable_models, on_delete=django.db.models.deletion.CASCADE, related_name='nfc_tags', to='contenttypes.contenttype', verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='nfctaggeditem',
            name='nfc_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='ntags.nfctag'),
        ),
        migrations.AddConstraint(
            model_name='nfctaggeditem',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'nfc_tag'), name='unique_content_object'),
        ),
        migrations.DeleteModel(
            name='NFCTagMemory',
        ),
    ]
