# Generated by Django 5.1 on 2024-10-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0008_nfctagtype_nfctag_nfc_tag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctagmemory',
            name='eeprom',
            field=models.BinaryField(max_length=924),
        ),
    ]
