# Generated by Django 5.1 on 2024-09-20 18:42

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0008_alter_nfctag_integrated_circuit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ntags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nfctagdesign',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nfctagdesign',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to=settings.AUTH_USER_MODEL),
        ),
    ]
