# Generated by Django 5.1 on 2024-10-16 03:38

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0008_remove_nfctagmemory_nfc_tag_alter_nfctag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctaggeditem',
            name='nfc_tag',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='ntags.nfctag'),
        ),
    ]
