# Generated by Django 5.1 on 2024-10-04 06:52

import django.db.models.deletion
import ntags.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ntags', '0009_alter_nfctagmemory_eeprom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctag',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=ntags.models.get_content_type_options, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ntags', to='contenttypes.contenttype'),
        ),
    ]
