# Generated by Django 5.1 on 2024-10-16 03:48

import django.db.models.deletion
import ntags
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ntags', '0009_alter_nfctaggeditem_nfc_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfctag',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=ntags.get_nfc_taggable_models, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfc_tags', to='contenttypes.contenttype', verbose_name='Content type'),
        ),
        migrations.AddField(
            model_name='nfctag',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.DeleteModel(
            name='NFCTaggedItem',
        ),
    ]
