# Generated by Django 5.1 on 2024-09-21 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ntags', '0009_alter_nfctag_user_alter_nfctagdesign_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctag',
            name='content',
        ),
        migrations.RemoveField(
            model_name='nfctag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='nfctag',
            name='last_modified',
        ),
        migrations.AlterField(
            model_name='nfctagdesign',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ntag_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NFCTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_tagged_items', to='contenttypes.contenttype')),
                ('nfc_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='ntags.nfctag')),
            ],
            options={
                'verbose_name': 'NFC Tagged Item',
                'verbose_name_plural': 'NFC Tagged Items',
                'unique_together': {('nfc_tag', 'content_type', 'object_id')},
            },
        ),
    ]
