# Generated by Django 5.1 on 2024-09-22 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0010_remove_nfctag_content_remove_nfctag_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctag',
            name='design',
        ),
        migrations.DeleteModel(
            name='NFCTagDesign',
        ),
    ]
