# Generated by Django 5.1 on 2024-10-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0010_nfctag_content_type_nfctag_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctag',
            name='integrated_circuit',
            field=models.CharField(choices=[('213', 'NTAG 213'), ('215', 'NTAG 215'), ('216', 'NTAG 216')], default='213', max_length=5),
        ),
    ]
