# Generated by Django 5.1 on 2024-10-04 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0010_alter_nfctag_content_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctagtype',
            name='collection',
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ntags', to=settings.AUTH_USER_MODEL),
        ),
    ]
