# Generated by Django 5.1 on 2024-10-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0012_alter_nfctag_managers_rename_eeprom_nfctag_metadata'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='nfctag',
            managers=[
            ],
        ),
    ]
