# Generated by Django 5.1 on 2024-10-17 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ntags', '0013_alter_nfctag_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nfctag',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_content_object'),
        ),
    ]
