# Generated by Django 5.1 on 2024-10-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0014_nfctag_unique_content_object'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfctagdesigngalleryimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'gallery image', 'verbose_name_plural': 'gallery images'},
        ),
    ]
