# Generated by Django 5.1 on 2024-10-20 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0015_alter_nfctagdesigngalleryimage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctag',
            name='label',
        ),
    ]
