# Generated by Django 5.1 on 2024-10-21 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0016_remove_nfctag_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfctag',
            options={'ordering': ['serial_number'], 'verbose_name': 'NFC Tag', 'verbose_name_plural': 'NFC Tags'},
        ),
        migrations.AlterModelOptions(
            name='nfctagdesign',
            options={'ordering': ['name'], 'verbose_name': 'NFC Tag Design', 'verbose_name_plural': 'NFC Tag Designs'},
        ),
        migrations.AlterModelOptions(
            name='nfctagdesigngalleryimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='nfctagscan',
            options={'verbose_name': 'NFC Tag Scan', 'verbose_name_plural': 'NFC Tag Scans'},
        ),
    ]
