# Generated by Django 5.1 on 2024-10-21 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0017_alter_nfctag_options_alter_nfctagdesign_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctagdesign',
            name='designer',
        ),
    ]
