# Generated by Django 5.1 on 2024-10-21 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0018_remove_nfctagdesign_designer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctag',
            name='design',
        ),
        migrations.RemoveField(
            model_name='nfctagdesigngalleryimage',
            name='design',
        ),
        migrations.RemoveField(
            model_name='nfctagdesigngalleryimage',
            name='image',
        ),
        migrations.DeleteModel(
            name='NFCTagDesign',
        ),
        migrations.DeleteModel(
            name='NFCTagDesignGalleryImage',
        ),
    ]
