# Generated by Django 5.1 on 2024-10-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntags', '0019_remove_nfctag_design_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfctag',
            options={'ordering': ['uid'], 'verbose_name': 'NFC Tag', 'verbose_name_plural': 'NFC Tags'},
        ),
        migrations.RenameField(
            model_name='nfctag',
            old_name='serial_number',
            new_name='uid',
        ),
    ]
