# Generated by Django 5.1 on 2024-09-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyindexpage_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyIndexPage',
        ),
    ]
