# Generated by Django 5.1 on 2024-10-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolioindexpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioindexpage',
            name='body',
        ),
    ]
