# Generated by Django 5.1 on 2024-09-09 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpage',
            name='trainer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
