# Generated by Django 5.1 on 2024-09-09 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_trainerpage_trainer'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='wagtailcore.collection'),
        ),
        migrations.AlterField(
            model_name='trainerpage',
            name='trainer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page', to=settings.AUTH_USER_MODEL),
        ),
    ]
