# Generated by Django 5.1 on 2024-09-09 04:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_trainer_collection_alter_trainerpage_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainerpage',
            name='body',
            field=wagtail.fields.StreamField([('inventory', 7)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('description', 2)]], {}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 2)]], {}), 5: ('wagtail.blocks.StructBlock', [[('plant', 3), ('nfc_tag', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('name', 0), ('description', 1), ('plants', 6)]], {})}),
        ),
    ]
