# Generated by Django 5.1 on 2024-09-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_rename_body_trainerpage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerpage',
            name='inventory',
        ),
    ]
