# Generated by Django 5.1 on 2024-09-17 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0006_remove_trainerpage_inventory'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'trainer', 'verbose_name_plural': 'trainers'},
        ),
        migrations.RemoveField(
            model_name='trainerpage',
            name='trainer',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection'),
        ),
    ]
