# Generated by Django 5.1 on 2024-09-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogTagIndexPage',
            new_name='TagIndexPage',
        ),
    ]
