# Generated by Django 5.1 on 2024-10-01 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_basedocument_options_alter_baseimage_options_and_more'),
        ('blog', '0003_alter_blogpagegalleryimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagegalleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.baseimage'),
        ),
    ]
