# Generated by Django 5.1 on 2024-09-08 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biodiversity', '0001_initial'),
        ('inventory', '0001_initial'),
        ('nearfieldcommunication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryplant',
            name='nfc_tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link', to='nearfieldcommunication.nfctag'),
        ),
        migrations.AddField(
            model_name='inventoryplant',
            name='plant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='biodiversity.plant'),
        ),
    ]
