# Generated by Django 5.1 on 2024-09-08 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerinventory',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryplant',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='inventory.trainerinventory'),
        ),
        migrations.AddIndex(
            model_name='trainerinventory',
            index=models.Index(fields=['trainer', 'name'], name='inventory_t_trainer_1eff79_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainerinventory',
            constraint=models.UniqueConstraint(fields=('trainer', 'name'), name='unique_trainer_inventory'),
        ),
        migrations.AddConstraint(
            model_name='inventoryplant',
            constraint=models.UniqueConstraint(fields=('inventory', 'plant', 'nfc_tag'), name='unique_inventory_plant'),
        ),
    ]
