# Generated by Django 5.1 on 2024-10-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0016_remove_plantgalleryimage_plant_and_more'),
        ('inventory', '0002_alter_inventoryindexcollection_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryBoxPage',
        ),
    ]
