# Generated by Django 5.1 on 2024-10-08 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryindexcollection_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryindexpage',
            name='user_collection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='page', to='inventory.inventoryindexcollection'),
        ),
    ]
