# Generated by Django 5.1 on 2024-09-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_boxitem_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxitem',
            options={'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.RemoveConstraint(
            model_name='boxitem',
            name='unique_box_item',
        ),
        migrations.RemoveIndex(
            model_name='boxitem',
            name='inventory_b_content_6aa1d5_idx',
        ),
        migrations.RemoveField(
            model_name='boxitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='boxitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='boxitem',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
