# Generated by Django 5.1 on 2024-09-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainerinventory',
            options={'verbose_name': 'inventory', 'verbose_name_plural': 'inventories'},
        ),
    ]
