# Generated by Django 5.1 on 2024-10-08 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryindexpage_user_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryindexpage',
            name='user_collection',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page', to='inventory.inventoryindexcollection'),
        ),
    ]
