# Generated by Django 5.1 on 2024-09-08 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0003_remove_plant_inventory'),
        ('inventory', '0003_trainerinventory_name_and_more'),
        ('nearfieldcommunication', '0004_rename_trainer_nfctag_user_remove_nfctag_plant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='inventory.trainerinventory')),
                ('nfc_tag', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link', to='nearfieldcommunication.nfctag')),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='biodiversity.plant')),
            ],
            options={
                'unique_together': {('inventory', 'plant', 'nfc_tag')},
            },
        ),
    ]
