# Generated by Django 5.1 on 2024-09-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryplant',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
