# Generated by Django 5.1 on 2024-09-17 03:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_trainerinventory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainerInventory',
            new_name='InventoryBox',
        ),
        migrations.AlterModelOptions(
            name='inventorybox',
            options={'verbose_name': 'box', 'verbose_name_plural': 'boxes'},
        ),
        migrations.RenameIndex(
            model_name='inventorybox',
            new_name='inventory_i_trainer_a7de0e_idx',
            old_name='inventory_t_trainer_1eff79_idx',
        ),
    ]
