# Generated by Django 5.1 on 2024-09-17 04:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_trainerinventory_inventorybox_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorybox',
            name='unique_trainer_inventory',
        ),
        migrations.RemoveIndex(
            model_name='inventorybox',
            name='inventory_i_trainer_a7de0e_idx',
        ),
        migrations.RenameField(
            model_name='inventorybox',
            old_name='trainer',
            new_name='owner',
        ),
        migrations.AddIndex(
            model_name='inventorybox',
            index=models.Index(fields=['owner', 'name'], name='inventory_i_owner_i_b2cca5_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybox',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_inventory'),
        ),
    ]
