# Generated by Django 5.1 on 2024-09-08 19:16

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryplant_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryplant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inventoryplant',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='inventoryplant',
            name='nfc_tag',
        ),
        migrations.RemoveField(
            model_name='inventoryplant',
            name='plant',
        ),
        migrations.RemoveIndex(
            model_name='trainerinventory',
            name='inventory_t_uuid_74c307_idx',
        ),
        migrations.AddField(
            model_name='trainerinventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainerinventory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainerinventory',
            name='slug',
            field=models.SlugField(default='default', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainerinventory',
            name='name',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AddIndex(
            model_name='trainerinventory',
            index=models.Index(fields=['trainer', 'name'], name='inventory_t_trainer_1eff79_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainerinventory',
            constraint=models.UniqueConstraint(fields=('trainer', 'name'), name='unique_trainer_inventory'),
        ),
        migrations.DeleteModel(
            name='InventoryPlant',
        ),
    ]
