# Generated by Django 5.1 on 2024-10-17 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0009_alter_userplant_box_alter_userplant_notes'),
        ('inventory', '0005_inventoryformpage_remove_inventoryboxpage_page_ptr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryBoxPage',
        ),
    ]
