# Generated by Django 5.1 on 2024-09-17 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventorybox_unique_trainer_inventory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryPlant',
        ),
    ]
