# Generated by Django 5.1 on 2024-09-08 19:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0004_alter_plant_name'),
        ('inventory', '0006_alter_inventoryplant_unique_together_and_more'),
        ('nearfieldcommunication', '0006_remove_nfctag_nearfieldco_serial__6c76a7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='inventory.trainerinventory')),
                ('nfc_tag', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link', to='nearfieldcommunication.nfctag')),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='biodiversity.plant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('inventory', 'plant', 'nfc_tag'), name='unique_inventory_plant')],
            },
        ),
    ]
