# Generated by Django 5.1 on 2024-09-17 06:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0003_remove_plant_nfc_tag'),
        ('inventory', '0007_delete_inventoryplant'),
        ('nearfieldcommunication', '0004_nfctag_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(db_index=True, max_length=25)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'box',
                'verbose_name_plural': 'boxes',
            },
        ),
        migrations.CreateModel(
            name='BoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.box')),
                ('nfc_tag', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_item', to='nearfieldcommunication.nfctag')),
                ('plant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='biodiversity.plant')),
            ],
            options={
                'verbose_name': 'box item',
                'verbose_name_plural': 'box items',
            },
        ),
        migrations.DeleteModel(
            name='InventoryBox',
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['owner', 'name'], name='inventory_b_owner_i_360465_idx'),
        ),
        migrations.AddConstraint(
            model_name='box',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_inventory'),
        ),
        migrations.AddConstraint(
            model_name='boxitem',
            constraint=models.UniqueConstraint(fields=('box', 'nfc_tag', 'plant'), name='unique_box_item'),
        ),
    ]
