# Generated by Django 5.1 on 2024-09-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_box_boxitem_delete_inventorybox_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='last_updated',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='boxitem',
            old_name='last_updated',
            new_name='last_modified',
        ),
    ]
