# Generated by Django 5.1 on 2024-09-18 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0010_remove_boxitem_unique_box_item_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='boxitem',
            name='unique_box_item',
        ),
        migrations.RemoveField(
            model_name='boxitem',
            name='plant',
        ),
        migrations.AddField(
            model_name='boxitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='boxitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='boxitem',
            index=models.Index(fields=['content_type', 'object_id'], name='inventory_b_content_6aa1d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='boxitem',
            constraint=models.UniqueConstraint(fields=('box', 'content_type', 'object_id'), name='unique_box_item'),
        ),
    ]
