# Generated by Django 5.1 on 2024-09-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_box_options_alter_boxitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='box',
            name='last_modified',
        ),
    ]
