# Generated by Django 5.1 on 2024-09-18 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_boximage_delete_boxgalleryimage'),
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boximage',
            name='box',
        ),
        migrations.RemoveField(
            model_name='boximage',
            name='image',
        ),
        migrations.AddField(
            model_name='box',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection'),
        ),
        migrations.AlterField(
            model_name='box',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BoxDocument',
        ),
        migrations.DeleteModel(
            name='BoxImage',
        ),
    ]
