# Generated by Django 5.1 on 2024-09-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_boximage_box_remove_boximage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
