# Generated by Django 5.0.6 on 2024-08-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_nearfieldcommunicationrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255)),
                ('vernacular_name', models.CharField(blank=True, max_length=255, null=True)),
                ('taxon_id', models.CharField(blank=True, max_length=50, null=True)),
                ('kingdom', models.CharField(blank=True, max_length=100, null=True)),
                ('kingdom_key', models.IntegerField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('taxonomic_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255)),
                ('vernacular_name', models.CharField(blank=True, max_length=255, null=True)),
                ('taxon_id', models.CharField(blank=True, max_length=50, null=True)),
                ('kingdom', models.CharField(blank=True, max_length=100, null=True)),
                ('kingdom_key', models.IntegerField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('taxonomic_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
