# Generated by Django 5.0.6 on 2024-08-17 06:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_animal_plant'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='scientific_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='scientific_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='kingdom',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='kingdom_key',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='taxonomic_status',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='vernacular_name',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='kingdom',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='kingdom_key',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='taxonomic_status',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='vernacular_name',
        ),
        migrations.AddField(
            model_name='animal',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection'),
        ),
        migrations.AddField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection'),
        ),
        migrations.AddField(
            model_name='plant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='taxon_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='taxon_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
