# Generated by Django 5.0.6 on 2024-08-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_rename_scientific_name_animal_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
