# Generated by Django 5.0.6 on 2024-08-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_remove_plant_collection_delete_animal_delete_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nearfieldcommunicationtag',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='nearfieldcommunicationtag',
            name='type',
        ),
        migrations.DeleteModel(
            name='NearFieldCommunicationRecord',
        ),
        migrations.DeleteModel(
            name='NearFieldCommunicationTag',
        ),
        migrations.DeleteModel(
            name='NearFieldCommunicationTagType',
        ),
    ]
