# Generated by Django 5.0.6 on 2024-08-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_remove_nearfieldcommunicationtag_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalgallerydocument',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='journalgalleryimage',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='journalgallerydocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='journalgalleryimage',
            name='image',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='JournalGalleryDocument',
        ),
        migrations.DeleteModel(
            name='JournalGalleryImage',
        ),
    ]
