# Generated by Django 5.0.6 on 2024-08-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_remove_journalgallerydocument_journal_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryassetpage',
            name='uuid',
        ),
    ]
