# Generated by Django 5.0.6 on 2024-08-17 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_remove_inventoryassetpage_collection_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryAssetPage',
        ),
        migrations.DeleteModel(
            name='TrainerInventoryPage',
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='name',
        ),
    ]
