# Generated by Django 5.0.6 on 2024-08-18 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_delete_inventoryassetpage_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionentity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventorycollection',
            name='description',
        ),
        migrations.AddIndex(
            model_name='collectionentity',
            index=models.Index(fields=['inventory_collection', 'name'], name='inventory_c_invento_680bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycollection',
            index=models.Index(fields=['user_inventory', 'name'], name='inventory_i_user_in_619683_idx'),
        ),
        migrations.AddIndex(
            model_name='userinventory',
            index=models.Index(fields=['user'], name='inventory_u_user_id_446a44_idx'),
        ),
    ]
