# Generated by Django 5.0.6 on 2024-08-18 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_remove_collectionentity_description_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectionEntity',
            new_name='InventoryEntity',
        ),
        migrations.RemoveConstraint(
            model_name='inventoryentity',
            name='unique_translation_key_locale_inventory_collectionentity',
        ),
        migrations.RenameIndex(
            model_name='inventoryentity',
            new_name='inventory_i_name_ab3478_idx',
            old_name='inventory_c_name_0dd4e5_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryentity',
            new_name='inventory_i_invento_7b0c75_idx',
            old_name='inventory_c_invento_680bfb_idx',
        ),
        migrations.AddConstraint(
            model_name='inventoryentity',
            constraint=models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_inventory_inventoryentity'),
        ),
    ]
