# Generated by Django 5.0.6 on 2024-08-18 01:10

import django.db.models.deletion
import wagtail.contrib.routable_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_rename_collectionentity_inventoryentity_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInventoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('user_inventory', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page', to='inventory.userinventory')),
            ],
            options={
                'verbose_name': 'user inventory page',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
