# Generated by Django 5.0.6 on 2024-08-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_userinventorypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycollection',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentity',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
