# Generated by Django 5.0.6 on 2024-08-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_inventorycollection_sort_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinventory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='inventorycollection',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryentity',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userinventory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
