# Generated by Django 5.0.6 on 2024-08-18 03:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_alter_userinventory_unique_together_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventorycollection',
            constraint=models.UniqueConstraint(fields=('user_inventory', 'slug'), name='unique_user_inventory_slug_inventory_inventorycollection'),
        ),
        migrations.AddConstraint(
            model_name='inventoryentity',
            constraint=models.UniqueConstraint(fields=('inventory_collection', 'slug'), name='unique_inventory_collection_slug_inventory_inventoryentity'),
        ),
    ]
