# Generated by Django 5.0.6 on 2024-08-18 16:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_inventorycollection_unique_user_inventory_slug_inventory_inventorycollection_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryentity',
            unique_together=None,
        ),
        migrations.CreateModel(
            name='InventoryCollectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'inventory collection page',
                'verbose_name_plural': 'inventory collection pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InventoryEntityPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'inventory entity page',
                'verbose_name_plural': 'inventory entity pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='inventoryentity',
            name='inventory_collection',
        ),
        migrations.RemoveField(
            model_name='inventoryentity',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='inventoryentity',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='inventoryentity',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='inventoryentity',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='inventoryentity',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinventorypage',
            name='user_inventory',
        ),
        migrations.RemoveField(
            model_name='inventoryindexpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='inventoryindexpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name='InventoryCollection',
        ),
    ]
