# Generated by Django 5.0.6 on 2024-08-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_inventorycollectionpage_inventoryentitypage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryEntity',
        ),
        migrations.DeleteModel(
            name='UserInventory',
        ),
        migrations.DeleteModel(
            name='UserInventoryPage',
        ),
    ]
