# Generated by Django 5.0.6 on 2024-08-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_inventorycollectionpage_collection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorycollectionpage',
            options={'verbose_name': 'inventory collection', 'verbose_name_plural': 'inventory collections'},
        ),
        migrations.AlterModelOptions(
            name='inventoryentitypage',
            options={'verbose_name': 'inventory entity', 'verbose_name_plural': 'inventory entity'},
        ),
        migrations.RemoveField(
            model_name='inventoryindexpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventoryuserpage',
            name='description',
        ),
        migrations.AddField(
            model_name='inventorycollectionpage',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorycollectionpage',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventorycollectionpage',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentitypage',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryentitypage',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='inventorycollectionpage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryentitypage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
