# Generated by Django 5.0.6 on 2024-08-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_alter_inventorycollectionpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycollectionpage',
            name='is_default',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
