# Generated by Django 5.0.6 on 2024-08-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_alter_inventorycollectionpage_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorycollectionpage',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='inventorycollectionpage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventoryentitypage',
            name='name',
        ),
        migrations.AddField(
            model_name='inventoryindexpage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryuserpage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
