# Generated by Django 5.0.6 on 2024-08-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_remove_inventorycollectionpage_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorycollectionpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventoryentitypage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventoryindexpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventoryuserpage',
            name='description',
        ),
        migrations.AddField(
            model_name='inventorycollectionpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='inventoryentitypage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='inventoryindexpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='inventoryuserpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
