# Generated by Django 5.0.6 on 2024-08-20 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_inventorycollectiongalleryimage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryCollectionGalleryImage',
        ),
    ]
