# Generated by Django 5.0.6 on 2024-08-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_inventoryentitytag_inventoryentitypage_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryIndexPage',
        ),
    ]
