# Generated by Django 5.0.6 on 2024-08-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0061_delete_inventoryindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryentitypage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='inventorycollectionpage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='inventoryentitypage',
            name='sort_order',
        ),
        migrations.DeleteModel(
            name='InventoryEntityTag',
        ),
    ]
