# Generated by Django 5.0.6 on 2024-08-21 22:51

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0063_inventorynfclink'),
        ('nearfieldcommunication', '0020_remove_nfctag_owner_nfctagscan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInventoryNfcLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfc_tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='nearfieldcommunication.nfctag')),
                ('page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventoryentitypage')),
                ('user_inventory', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_links', to='inventory.userinventory')),
            ],
        ),
        migrations.DeleteModel(
            name='InventoryNfcLink',
        ),
    ]
