# Generated by Django 5.0.6 on 2024-08-21 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_userinventory_userinventorynfclink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinventorynfclink',
            name='user_inventory',
        ),
        migrations.AddField(
            model_name='userinventorynfclink',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserInventory',
        ),
    ]
