# Generated by Django 5.0.6 on 2024-08-22 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_nfctagpagelink_delete_userinventorynfclink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctagpagelink',
            name='page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_link', to='inventory.inventoryentitypage'),
        ),
    ]
