# Generated by Django 5.0.6 on 2024-08-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_alter_nfctagpagelink_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NfcTagPageLink',
        ),
    ]
