# Generated by Django 5.0.6 on 2024-08-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_delete_nfctagpagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycollectionpage',
            name='inventory_type',
            field=models.CharField(choices=[('U', 'User'), ('C', 'Collection'), ('E', 'Entity')], default='E', max_length=2),
        ),
        migrations.AddField(
            model_name='inventoryentitypage',
            name='inventory_type',
            field=models.CharField(choices=[('U', 'User'), ('C', 'Collection'), ('E', 'Entity')], default='E', max_length=2),
        ),
        migrations.AddField(
            model_name='inventoryuserpage',
            name='inventory_type',
            field=models.CharField(choices=[('U', 'User'), ('C', 'Collection'), ('E', 'Entity')], default='E', max_length=2),
        ),
    ]
