# Generated by Django 5.0.6 on 2024-08-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_inventorycollectionpage_inventory_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryentitypage',
            options={'verbose_name': 'inventory entity', 'verbose_name_plural': 'inventory entities'},
        ),
        migrations.AddField(
            model_name='inventorycollectionpage',
            name='is_party',
            field=models.BooleanField(default=False),
        ),
    ]
