# Generated by Django 5.0.6 on 2024-08-26 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0071_rename_inventorycollectionpage_inventorybox'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryUserPage',
            new_name='UserInventory',
        ),
    ]
