# Generated by Django 5.0.6 on 2024-08-26 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0072_rename_inventoryuserpage_userinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorybox',
            options={'verbose_name': 'box', 'verbose_name_plural': 'boxes'},
        ),
        migrations.AlterModelOptions(
            name='userinventory',
            options={'verbose_name': 'inventory', 'verbose_name_plural': 'inventories'},
        ),
    ]
