# Generated by Django 5.0.6 on 2024-08-26 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0073_alter_inventorybox_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorybox',
            old_name='intro',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='inventoryentitypage',
            old_name='intro',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='userinventory',
            old_name='intro',
            new_name='description',
        ),
    ]
