# Generated by Django 5.0.6 on 2024-08-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0074_rename_intro_inventorybox_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorybox',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='inventoryentitypage',
            name='collection',
        ),
        migrations.AlterField(
            model_name='inventorybox',
            name='inventory_type',
            field=models.CharField(choices=[('U', 'User'), ('B', 'Box'), ('E', 'Entity')], default='E', max_length=2),
        ),
        migrations.AlterField(
            model_name='inventoryentitypage',
            name='inventory_type',
            field=models.CharField(choices=[('U', 'User'), ('B', 'Box'), ('E', 'Entity')], default='E', max_length=2),
        ),
        migrations.AlterField(
            model_name='userinventory',
            name='inventory_type',
            field=models.CharField(choices=[('U', 'User'), ('B', 'Box'), ('E', 'Entity')], default='E', max_length=2),
        ),
    ]
