# Generated by Django 5.0.6 on 2024-08-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0075_remove_inventorybox_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorybox',
            name='inventory_type',
        ),
        migrations.RemoveField(
            model_name='inventoryentitypage',
            name='inventory_type',
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='inventory_type',
        ),
    ]
