# Generated by Django 5.0.6 on 2024-08-26 20:48

import django.db.models.deletion
import modelcluster.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0076_remove_inventorybox_inventory_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryentitypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='inventoryentitygalleryimage',
            name='page',
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('is_party', models.BooleanField(default=False)),
                ('user_inventory', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='inventory.userinventory')),
            ],
            options={
                'verbose_name': 'box',
                'verbose_name_plural': 'boxes',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('inventory_box', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='inventory.box')),
            ],
            options={
                'verbose_name': 'entity',
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.AddField(
            model_name='inventoryentitygalleryimage',
            name='entity',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='inventory.entity'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InventoryBox',
        ),
        migrations.DeleteModel(
            name='InventoryEntityPage',
        ),
    ]
