# Generated by Django 5.0.6 on 2024-08-26 20:59

import django.db.models.deletion
import modelcluster.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_footerparagraph_unique_together_and_more'),
        ('inventory', '0077_remove_inventoryentitypage_page_ptr_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryEntityGalleryImage',
            new_name='EntityGalleryImage',
        ),
        migrations.AddField(
            model_name='box',
            name='locale',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='box',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='locale',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='entity',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='user_inventory',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='inventory.userinventory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box',
            name='user_inventory',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='inventory.userinventory'),
        ),
        migrations.AddConstraint(
            model_name='box',
            constraint=models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_inventory_box'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_inventory_entity'),
        ),
    ]
