# Generated by Django 5.0.6 on 2024-08-26 21:17

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0078_rename_inventoryentitygalleryimage_entitygalleryimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='user_inventory',
        ),
        migrations.AddField(
            model_name='box',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='user_inventory',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='inventory.userinventory'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='inventory_box',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='inventory.box'),
        ),
    ]
