# Generated by Django 5.0.6 on 2024-08-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0079_remove_entity_user_inventory_box_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
