# Generated by Django 5.0.6 on 2024-08-27 00:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0080_box_url_entity_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='url',
            field=models.URLField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='url',
            field=models.URLField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
