# Generated by Django 5.0.6 on 2024-08-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0081_alter_box_url_alter_box_uuid_alter_entity_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='url',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='url',
        ),
    ]
