# Generated by Django 5.1 on 2024-08-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0083_alter_box_locale_alter_entity_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
