# Generated by Django 5.1 on 2024-08-27 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0084_alter_box_name_alter_entity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinventory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
