# Generated by Django 5.1 on 2024-08-27 19:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0085_userinventory_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinventory',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
