# Generated by Django 5.1 on 2024-08-28 19:34

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0086_alter_userinventory_uuid'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='box',
            name='user_inventory',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='inventory_box',
        ),
        migrations.AddField(
            model_name='entity',
            name='inventory',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='inventory.userinventory'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['name', 'slug', 'uuid'], name='inventory_e_name_c9686e_idx'),
        ),
        migrations.DeleteModel(
            name='Box',
        ),
    ]
