# Generated by Django 5.1 on 2024-08-29 02:01

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0087_remove_box_locale_remove_box_user_inventory_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entity',
            name='unique_translation_key_locale_inventory_entity',
        ),
        migrations.RemoveIndex(
            model_name='entity',
            name='inventory_e_name_c9686e_idx',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='translation_key',
        ),
        migrations.AddField(
            model_name='entity',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection'),
        ),
        migrations.AddField(
            model_name='entity',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinventory',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
