# Generated by Django 5.1 on 2024-08-29 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0089_inventoryindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryindex',
            options={'verbose_name': 'inventory index'},
        ),
        migrations.AlterModelOptions(
            name='userinventory',
            options={'verbose_name': 'user inventory', 'verbose_name_plural': 'user inventories'},
        ),
    ]
