# Generated by Django 5.1 on 2024-08-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0090_alter_inventoryindex_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='date',
        ),
    ]
