# Generated by Django 5.1 on 2024-08-30 04:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0091_remove_entity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinventory',
            name='contents',
            field=wagtail.fields.StreamField([('heading_block', 1), ('entity_block', 6)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['inventory.UserInventory', 'inventory.Entity'], 'required': True}), 1: ('wagtail.blocks.StructBlock', [[('page', 0)]], {}), 2: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['inventory.Entity'], 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'required': True}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('icon', 4)]], {}), 6: ('wagtail.blocks.StructBlock', [[('entity', 2), ('link', 5)]], {})}, help_text='Use this section to list your entities.'),
        ),
    ]
