# Generated by Django 5.1 on 2024-08-30 04:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0093_alter_userinventory_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinventory',
            name='contents',
            field=wagtail.fields.StreamField([('entities', 4)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['inventory.Entity'], 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 1), ('icon', 2)]], {}), 4: ('wagtail.blocks.StructBlock', [[('entity', 0), ('link', 3)]], {})}),
        ),
    ]
