# Generated by Django 5.1 on 2024-08-30 04:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0094_alter_userinventory_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinventory',
            name='contents',
            field=wagtail.fields.StreamField([('entities', 1)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['inventory.Entity'], 'required': True}), 1: ('wagtail.blocks.StructBlock', [[('entity', 0)]], {})}),
        ),
    ]
