# Generated by Django 5.1 on 2024-08-30 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0095_alter_userinventory_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinventory',
            name='contents',
        ),
    ]
