# Generated by Django 5.1 on 2024-09-01 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0096_remove_userinventory_contents'),
        ('nearfieldcommunication', '0028_remove_nfctag_entity_nfctag_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='nfc_tag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nearfieldcommunication.nfctag'),
        ),
        migrations.AddField(
            model_name='inventoryindex',
            name='nfc_tag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nearfieldcommunication.nfctag'),
        ),
        migrations.AddField(
            model_name='userinventory',
            name='nfc_tag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nearfieldcommunication.nfctag'),
        ),
    ]
