# Generated by Django 5.1 on 2024-09-01 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0097_entity_nfc_tag_inventoryindex_nfc_tag_and_more'),
        ('nearfieldcommunication', '0029_remove_nfctag_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryindex',
            name='nfc_tag',
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='nfc_tag',
        ),
        migrations.AlterField(
            model_name='entity',
            name='nfc_tag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_entity', to='nearfieldcommunication.nfctag'),
        ),
    ]
