# Generated by Django 5.1 on 2024-09-07 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0098_remove_inventoryindex_nfc_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitygalleryimage',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='entitygalleryimage',
            name='image',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='EntityGalleryImage',
        ),
    ]
