# Generated by Django 5.1 on 2024-09-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0099_remove_entitygalleryimage_entity_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryindex',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='inventoryindex',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='body',
        ),
        migrations.AddIndex(
            model_name='userinventory',
            index=models.Index(fields=['uuid'], name='inventory_u_uuid_6fbfc5_idx'),
        ),
        migrations.DeleteModel(
            name='InventoryIndex',
        ),
    ]
