# Generated by Django 5.1 on 2024-09-07 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0101_inventoryplant'),
        ('nearfieldcommunication', '0031_nfctag_content_nfctag_url'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventoryplant',
            name='inventory_i_uuid_9699b6_idx',
        ),
        migrations.AddField(
            model_name='inventoryplant',
            name='nfc_tag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant', to='nearfieldcommunication.nfctag'),
        ),
        migrations.AddIndex(
            model_name='inventoryplant',
            index=models.Index(fields=['uuid', 'slug'], name='inventory_i_uuid_59322f_idx'),
        ),
    ]
