# Generated by Django 5.1 on 2024-09-07 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0102_remove_inventoryplant_inventory_i_uuid_9699b6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryplant',
            name='quantity',
        ),
    ]
