# Generated by Django 5.1 on 2024-09-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0103_remove_inventoryplant_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryPlant',
        ),
    ]
