# Generated by Django 5.1 on 2024-10-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basedocument',
            options={'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
        migrations.AlterModelOptions(
            name='baseimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='basedocument',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='basedocument',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='baseimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='baseimage',
            name='sort_order',
        ),
    ]
