# Generated by Django 5.1 on 2024-09-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseimage',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
