# Generated by Django 5.1 on 2024-10-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_navigationsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationsettings',
            old_name='instagtram_url',
            new_name='instagram_url',
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone number'),
        ),
    ]
