# Generated by Django 5.1 on 2024-10-21 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_baseimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basedocument',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='baseimage',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='baserendition',
            options={'verbose_name': 'Rendition', 'verbose_name_plural': 'Renditions'},
        ),
        migrations.AlterModelOptions(
            name='navigationsettings',
            options={'verbose_name': 'Navigation Settings', 'verbose_name_plural': 'Navigation Settings'},
        ),
    ]
