# Generated by Django 5.0.6 on 2024-08-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_baseimage_caption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterBanner',
        ),
    ]
