# Generated by Django 5.0.6 on 2024-08-20 22:23

import django.db.models.deletion
import uuid
import wagtail.fields
import wagtail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_delete_footerbanner'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='footerparagraph',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='footerparagraph',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='footerparagraph',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='footerparagraph',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='chat_link',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='mastodon_url',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='twitter_url',
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('body', wagtail.fields.RichTextField(max_length=100)),
                ('copyright', models.TextField(max_length=100)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
            ],
            options={
                'verbose_name': 'Footer Body',
                'verbose_name_plural': 'Footer Bodies',
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
            bases=(wagtail.models.PreviewableMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='FooterCopyright',
        ),
        migrations.DeleteModel(
            name='FooterParagraph',
        ),
    ]
