# Generated by Django 5.1 on 2024-09-24 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('ntags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_item', to='home.userpage')),
                ('nfc_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_links', to='ntags.nfctag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userpage',
            name='nfc_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page', to='home.userpagetag'),
        ),
    ]
