# Generated by Django 5.1 on 2024-09-24 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userpagetag_userpage_nfc_tags'),
        ('ntags', '0003_delete_nfctaglink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpage',
            name='nfc_tags',
        ),
        migrations.AddField(
            model_name='userpage',
            name='nfc_tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page', to='ntags.nfctag'),
        ),
        migrations.DeleteModel(
            name='UserPageTag',
        ),
    ]
