# Generated by Django 5.1 on 2024-09-20 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_usercollection_userpage_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpage',
            name='collection',
        ),
        migrations.AddField(
            model_name='userpage',
            name='user_collection',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='page', to='home.usercollection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='collection',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.collection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collection', to=settings.AUTH_USER_MODEL),
        ),
    ]
