# Generated by Django 5.1 on 2024-09-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_userindexpage_nfc_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
