# Generated by Django 5.1 on 2024-09-27 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userformpage_alter_userindexpage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userformpage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='userformpage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='userformpage',
            name='to_address',
        ),
    ]
