# Generated by Django 5.1 on 2024-09-27 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_userformpage_from_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userformpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='UserFormField',
        ),
        migrations.DeleteModel(
            name='UserFormPage',
        ),
    ]
