# Generated by Django 5.0.6 on 2024-08-20 22:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantbanner',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='assistantbanner',
            name='cta_url',
        ),
        migrations.AddField(
            model_name='assistantbanner',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
