# Generated by Django 5.1 on 2024-09-07 23:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAssistant',
            new_name='TrainerAssistant',
        ),
        migrations.AlterModelOptions(
            name='trainerassistant',
            options={'verbose_name': 'Trainer Chat Bot', 'verbose_name_plural': 'Trainer Chat Bots'},
        ),
        migrations.RenameField(
            model_name='trainerassistant',
            old_name='user',
            new_name='trainer',
        ),
    ]
