# Generated by Django 5.0.6 on 2024-08-23 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_remove_assistantbanner_cta_text_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantbanner',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='assistantbanner',
            name='title',
        ),
        migrations.AddField(
            model_name='assistantbanner',
            name='page',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistantbanner',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
