# Generated by Django 5.0.6 on 2024-08-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_remove_assistantbanner_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantbanner',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='assistantbanner',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='assistantbanner',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='assistantbanner',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='assistantbanner',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='assistantbanner',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='assistantbanner',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='assistantbanner',
            name='live',
        ),
        migrations.RemoveField(
            model_name='assistantbanner',
            name='live_revision',
        ),
    ]
