# Generated by Django 5.0.6 on 2024-08-26 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_remove_assistantbanner_expire_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Chat Bot',
                'verbose_name_plural': 'User Chat Bots',
            },
        ),
        migrations.DeleteModel(
            name='AssistantBanner',
        ),
    ]
