# Generated by Django 5.1 on 2024-09-17 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0001_initial'),
        ('nearfieldcommunication', '0004_nfctag_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='nfc_tag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_plant', to='nearfieldcommunication.nfctag'),
        ),
    ]
