# Generated by Django 5.1 on 2024-09-08 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0001_initial'),
        ('inventory', '0003_trainerinventory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='inventory.trainerinventory'),
            preserve_default=False,
        ),
    ]
