# Generated by Django 5.1 on 2024-09-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0002_plant_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='inventory',
        ),
    ]
