# Generated by Django 5.1 on 2024-09-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0003_remove_plant_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
