# Generated by Django 5.1 on 2024-09-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0005_plant_expire_at_plant_expired_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='last_modified',
        ),
    ]
