# Generated by Django 5.1 on 2024-09-18 08:39

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0006_remove_plant_created_at_remove_plant_last_modified'),
        ('wagtaildocs', '0013_delete_uploadeddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document')),
                ('plant', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='biodiversity.plant')),
            ],
            options={
                'verbose_name': 'plant document',
                'verbose_name_plural': 'plant documents',
            },
        ),
    ]
