# Generated by Django 5.1 on 2024-09-18 16:07

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
        ('biodiversity', '0007_plantdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.baseimage')),
                ('plant', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='biodiversity.plant')),
            ],
            options={
                'verbose_name': 'plant image',
                'verbose_name_plural': 'plant images',
            },
        ),
        migrations.DeleteModel(
            name='PlantGalleryImage',
        ),
    ]
