# Generated by Django 5.1 on 2024-09-18 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0008_plantimage_delete_plantgalleryimage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='plantimage',
            name='plant',
        ),
        migrations.AddField(
            model_name='plant',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection'),
        ),
        migrations.DeleteModel(
            name='PlantDocument',
        ),
        migrations.DeleteModel(
            name='PlantImage',
        ),
    ]
