# Generated by Django 5.1 on 2024-09-18 22:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Plant = apps.get_model("biodiversity", "Plant")
    for row in Plant.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0009_remove_plantimage_image_remove_plantimage_plant_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plant',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AddField(
            model_name='plant',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['owner', 'name'], name='biodiversit_owner_i_45bc11_idx'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_plant'),
        ),
    ]
