# Generated by Django 5.1 on 2024-09-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0010_plant_owner_plant_slug_plant_uuid_and_more'),
    ]

    operations = [
    ]
