# Generated by Django 5.1 on 2024-09-18 22:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0011_auto_20240918_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
