# Generated by Django 5.0.6 on 2024-08-17 06:27

import django.db.models.deletion
import modelcluster.fields
import nearfieldcommunication.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0035_rename_scientific_name_animal_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NfcTagType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('form', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'nfc tag type',
                'verbose_name_plural': 'nfc tag types',
            },
        ),
        migrations.CreateModel(
            name='NfcTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('serial_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True, validators=[nearfieldcommunication.validators.validate_serial_number])),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nearfieldcommunication.nfctagtype')),
            ],
            options={
                'verbose_name': 'nfc tag',
                'verbose_name_plural': 'nfc tags',
            },
        ),
        migrations.CreateModel(
            name='NfcRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventoryassetpage')),
                ('tag', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndef_records', to='nearfieldcommunication.nfctag')),
            ],
            options={
                'verbose_name': 'nfc record',
                'verbose_name_plural': 'nfc records',
            },
        ),
    ]
