# Generated by Django 5.0.6 on 2024-08-17 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nearfieldcommunication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfcrecord',
            name='asset',
        ),
        migrations.AddField(
            model_name='nfcrecord',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfcrecord',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
