# Generated by Django 5.1 on 2024-09-08 15:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0002_rename_user_nfctag_trainer_nfctag_plant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nfctagscan',
            name='nearfieldco_counter_596e66_idx',
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='nfc_tag_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='nearfieldcommunication.nfctagtype'),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nfc_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='nfctagscan',
            name='counter',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='nfctagscan',
            index=models.Index(fields=['nfc_tag', 'scanned_at', 'counter'], name='nearfieldco_nfc_tag_6218fe_idx'),
        ),
    ]
