# Generated by Django 5.1 on 2024-09-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0003_remove_nfctagscan_nearfieldco_counter_596e66_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfctag',
            old_name='trainer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='nfctag',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='nfctagtype',
            name='integrated_circuit',
        ),
        migrations.AddField(
            model_name='nfctag',
            name='integrated_circuit',
            field=models.CharField(choices=[('213', 'NTAG 213'), ('215', 'NTAG 215'), ('216', 'NTAG 216')], default='213', max_length=5),
        ),
    ]
