# Generated by Django 5.0.6 on 2024-08-17 07:04

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0003_migrate_nfctags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfcrecord',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='nfctag',
            name='type',
        ),
        migrations.AddField(
            model_name='nfcrecord',
            name='nfc_tag',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='nearfieldcommunication.nfctag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfctag',
            name='tag_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='nearfieldcommunication.nfctagtype'),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
