# Generated by Django 5.1 on 2024-09-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0003_remove_nfctag_integrated_circuit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfctag',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
