# Generated by Django 5.1 on 2024-09-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0004_rename_trainer_nfctag_user_remove_nfctag_plant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctag',
            name='user',
        ),
    ]
