# Generated by Django 5.1 on 2024-09-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0004_nfctag_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctag',
            name='label',
        ),
    ]
