# Generated by Django 5.1 on 2024-09-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0005_remove_nfctag_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nfctag',
            name='nearfieldco_serial__6c76a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='nfctagscan',
            name='nearfieldco_nfc_tag_6218fe_idx',
        ),
    ]
