# Generated by Django 5.0.6 on 2024-08-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0005_nfctagtype_created_at_nfctagtype_last_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfctagtype',
            old_name='form',
            new_name='size',
        ),
    ]
