# Generated by Django 5.0.6 on 2024-08-17 09:05

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0006_rename_form_nfctagtype_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctagtype',
            name='size',
        ),
        migrations.AddField(
            model_name='nfctagtype',
            name='integrated_circuit',
            field=models.CharField(choices=[('213', 'Ntag 213'), ('215', 'Ntag 215'), ('216', 'Ntag 216')], default='213', max_length=5),
        ),
        migrations.AddField(
            model_name='nfctagtype',
            name='material',
            field=wagtail.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nfctagtype',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
