# Generated by Django 5.0.6 on 2024-08-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0007_remove_nfctagtype_size_nfctagtype_integrated_circuit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctagtype',
            name='material',
        ),
    ]
