# Generated by Django 5.1 on 2024-09-17 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0007_remove_nfctagtype_integrated_circuit_nfctagmemory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctag',
            name='url',
        ),
        migrations.DeleteModel(
            name='NfcTagMemory',
        ),
    ]
