# Generated by Django 5.0.6 on 2024-08-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nearfieldcommunication', '0008_remove_nfctagtype_material'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NfcRecord',
            new_name='NfcDataExchangeFormatRecord',
        ),
        migrations.RenameField(
            model_name='nfctag',
            old_name='tag_type',
            new_name='nfc_tag_type',
        ),
    ]
