# Generated by Django 5.0.6 on 2024-08-18 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0009_rename_nfcrecord_nfcdataexchangeformatrecord_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfcdataexchangeformatrecord',
            options={'verbose_name': 'ndef record', 'verbose_name_plural': 'ndef records'},
        ),
        migrations.RemoveField(
            model_name='nfcdataexchangeformatrecord',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='nfcdataexchangeformatrecord',
            name='object_id',
        ),
        migrations.AddField(
            model_name='nfcdataexchangeformatrecord',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page'),
        ),
    ]
