# Generated by Django 5.1 on 2024-09-17 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0010_nfctag_content_type_nfctag_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctag',
            name='uuid',
        ),
    ]
