# Generated by Django 5.1 on 2024-09-18 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nearfieldcommunication', '0011_remove_nfctag_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctag',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'trainers'), ('model', 'Trainer')), models.Q(('app_label', 'biodiversity'), ('model', 'Plant')), models.Q(('app_label', 'inventory'), ('model', 'Box')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
