# Generated by Django 5.0.6 on 2024-08-19 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0012_nfctag_page_delete_nfctaglink'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctag',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
