# Generated by Django 5.0.6 on 2024-08-19 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0013_alter_nfctag_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfctag',
            old_name='page',
            new_name='linked_page',
        ),
    ]
