# Generated by Django 5.1 on 2024-09-18 07:22

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0013_nfctag_label_nfctagtype_expire_at_nfctagtype_expired_and_more'),
    ]

    operations = [
        BootstrapTranslatableModel('nearfieldcommunication.NfcTagType'),
    ]
