# Generated by Django 5.1 on 2024-09-18 07:30

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0014_auto_20240918_0722'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctagtype',
            name='description',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='nfctagtype',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
        ),
        migrations.AlterField(
            model_name='nfctagtype',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='nfctagtype',
            unique_together={('translation_key', 'locale')},
        ),
    ]
