# Generated by Django 5.1 on 2024-09-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0015_alter_nfctagtype_description_alter_nfctagtype_locale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctagtype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='nfctagtype',
            name='last_modified',
        ),
    ]
