# Generated by Django 5.0.6 on 2024-08-21 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0061_delete_inventoryindexpage'),
        ('nearfieldcommunication', '0016_alter_nfctag_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctag',
            name='linked_page',
        ),
        migrations.AddField(
            model_name='nfctag',
            name='entity_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventoryentitypage'),
        ),
    ]
