# Generated by Django 5.0.6 on 2024-08-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0017_remove_nfctag_linked_page_nfctag_entity_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctag',
            name='label',
        ),
    ]
