# Generated by Django 5.1 on 2024-09-18 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0018_nfctagtypeimage_delete_nfctagtypegalleryimage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctagtypeimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='nfctagtypeimage',
            name='nfc_tag_type',
        ),
        migrations.AddField(
            model_name='nfctagtype',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection'),
        ),
        migrations.DeleteModel(
            name='NfcTagTypeDocument',
        ),
        migrations.DeleteModel(
            name='NfcTagTypeImage',
        ),
    ]
