# Generated by Django 5.0.6 on 2024-08-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0018_remove_nfctag_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctag',
            name='entity_page',
        ),
    ]
