# Generated by Django 5.1 on 2024-09-18 22:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0019_remove_nfctagtypeimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfctagtype',
            name='slug',
            field=models.SlugField(null=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nfctagtype',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
