# Generated by Django 5.1 on 2024-09-18 22:11

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    NfcTagType = apps.get_model("nearfieldcommunication", "NfcTagType")
    for row in NfcTagType.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0020_nfctagtype_slug_nfctagtype_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
