# Generated by Django 5.0.6 on 2024-08-22 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0020_remove_nfctag_owner_nfctagscan'),
        ('wagtailcore', '0093_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NfcTagPageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfc_tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='nearfieldcommunication.nfctag')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_links', to=settings.AUTH_USER_MODEL)),
                ('page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_link', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'nfc link',
                'verbose_name_plural': 'nfc links',
            },
        ),
    ]
