# Generated by Django 5.0.6 on 2024-08-22 16:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0021_nfctagpagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfctagpagelink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfctagpagelink',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
