# Generated by Django 5.1 on 2024-09-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0022_auto_20240918_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctagtype',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
