# Generated by Django 5.0.6 on 2024-08-23 20:49

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0022_nfctagpagelink_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctagpagelink',
            name='owner',
        ),
        migrations.AddField(
            model_name='nfctag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nfctagtype',
            name='description',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='nfctagtype',
            name='integrated_circuit',
            field=models.CharField(choices=[('213', 'NTAG 213'), ('215', 'NTAG 215'), ('216', 'NTAG 216')], default='213', max_length=5),
        ),
    ]
