# Generated by Django 5.0.6 on 2024-08-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0081_alter_box_url_alter_box_uuid_alter_entity_url_and_more'),
        ('nearfieldcommunication', '0024_remove_nfctagpagelink_page_nfctagpagelink_entity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NfcTagPageLink',
            new_name='NfcTagEntityLink',
        ),
    ]
