# Generated by Django 5.0.6 on 2024-08-27 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0082_remove_box_url_remove_entity_url'),
        ('nearfieldcommunication', '0025_rename_nfctagpagelink_nfctagentitylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfctag',
            name='entity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_link', to='inventory.entity'),
        ),
        migrations.DeleteModel(
            name='NfcTagEntityLink',
        ),
    ]
