# Generated by Django 5.1 on 2024-09-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0027_alter_nfctagscan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctag',
            name='entity',
        ),
        migrations.AddField(
            model_name='nfctag',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
