# Generated by Django 5.1 on 2024-09-01 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0028_remove_nfctag_entity_nfctag_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctag',
            name='url',
        ),
    ]
