# Generated by Django 5.1 on 2024-09-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0029_remove_nfctag_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctagtype',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
