# Generated by Django 5.1 on 2024-09-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0030_alter_nfctagtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfctag',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfctag',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
