# Generated by Django 5.1 on 2024-09-29 16:46

import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtail.models
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBox',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('collection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.collection')),
            ],
            options={
                'verbose_name': 'box',
                'verbose_name_plural': 'boxes',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('box', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='botany.inventorybox')),
                ('collection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.collection')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'plant',
                'verbose_name_plural': 'plants',
                'abstract': False,
                'indexes': [models.Index(fields=['box', 'name'], name='botany_plan_box_id_414d6e_idx')],
                'constraints': [models.UniqueConstraint(fields=('box', 'name'), name='unique_plant_name_in_box')],
                'unique_together': {('translation_key', 'locale')},
            },
            bases=(wagtail.search.index.Indexed, wagtail.models.PreviewableMixin, models.Model),
        ),
    ]
