# Generated by Django 5.1 on 2024-10-08 09:03

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('botany', '0001_initial'),
        ('inventory', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='inventory.inventoryboxpage'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
        ),
        migrations.AddField(
            model_name='userplantgalleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.baseimage'),
        ),
        migrations.AddField(
            model_name='userplantgalleryimage',
            name='plant',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='botany.userplant'),
        ),
        migrations.AddIndex(
            model_name='userplant',
            index=models.Index(fields=['box', 'name'], name='botany_user_box_id_543c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='userplant',
            index=models.Index(fields=['box', 'slug'], name='botany_user_box_id_e14445_idx'),
        ),
        migrations.AddConstraint(
            model_name='userplant',
            constraint=models.UniqueConstraint(fields=('box', 'name'), name='unique_plant_name_in_box'),
        ),
        migrations.AddConstraint(
            model_name='userplant',
            constraint=models.UniqueConstraint(fields=('box', 'slug'), name='unique_plant_slug_in_box'),
        ),
        migrations.AlterUniqueTogether(
            name='userplant',
            unique_together={('translation_key', 'locale')},
        ),
    ]
