# Generated by Django 5.1 on 2024-09-30 03:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0002_remove_inventorybox_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='botany.inventorybox'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
