# Generated by Django 5.1 on 2024-09-30 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0003_plant_sort_order_alter_plant_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
