# Generated by Django 5.1 on 2024-09-30 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0004_plant_created_at_plant_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post date'),
            preserve_default=False,
        ),
    ]
