# Generated by Django 5.1 on 2024-10-15 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0005_alter_userplant_user'),
        ('inventory', '0004_alter_inventoryindexpage_user_collection'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userplant',
            name='unique_plant_name_user',
        ),
        migrations.RemoveIndex(
            model_name='userplant',
            name='botany_user_user_id_44496c_idx',
        ),
        migrations.RemoveField(
            model_name='userplant',
            name='user',
        ),
        migrations.AddField(
            model_name='userplant',
            name='box',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='inventory.inventoryboxpage'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='userplant',
            index=models.Index(fields=['box', 'name'], name='botany_user_box_id_543c5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='userplant',
            constraint=models.UniqueConstraint(fields=('box', 'name'), name='unique_plant_name_in_box'),
        ),
    ]
