# Generated by Django 5.1 on 2024-09-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0005_plant_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
