# Generated by Django 5.1 on 2024-10-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0006_alter_plant_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorybox',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='collection',
        ),
    ]
