# Generated by Django 5.1 on 2024-10-17 20:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0008_userplant_notes'),
        ('inventory', '0005_inventoryformpage_remove_inventoryboxpage_page_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='inventory.inventoryformpage'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='notes',
            field=wagtail.fields.StreamField([('note', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.DateBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('date', 1), ('image', 2), ('body', 3)]], {})}),
        ),
    ]
