# Generated by Django 5.1 on 2024-10-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0009_alter_userplant_box_alter_userplant_notes'),
        ('inventory', '0006_delete_inventoryboxpage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='slug',
            field=models.SlugField(default='test', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='userplant',
            index=models.Index(fields=['box', 'slug'], name='botany_user_box_id_e14445_idx'),
        ),
        migrations.AddConstraint(
            model_name='userplant',
            constraint=models.UniqueConstraint(fields=('box', 'slug'), name='unique_plant_slug_in_box'),
        ),
    ]
