# Generated by Django 5.1 on 2024-10-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0010_plant_botany_plan_box_id_0387f8_idx_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryBox',
            new_name='UserBoxPage',
        ),
    ]
