# Generated by Django 5.1 on 2024-10-18 19:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0010_userplant_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userplantgalleryimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'gallery image', 'verbose_name_plural': 'gallery images'},
        ),
        migrations.AlterField(
            model_name='userplant',
            name='notes',
            field=wagtail.fields.StreamField([('note', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.DateBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('date', 1), ('image', 2), ('body', 3)]], {})}),
        ),
    ]
