# Generated by Django 5.1 on 2024-10-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0011_alter_userplantgalleryimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
