# Generated by Django 5.1 on 2024-10-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0011_rename_inventorybox_userboxpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userboxpage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
