# Generated by Django 5.1 on 2024-10-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0012_plant_quantity_alter_plant_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userboxpage',
            name='page_ptr',
        ),
    ]
