# Generated by Django 5.1 on 2024-10-20 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0012_userplant_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSubstrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Plant Substrate',
                'verbose_name_plural': 'Plant Substrates',
            },
        ),
        migrations.CreateModel(
            name='SubstrateMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('substrates', models.ManyToManyField(related_name='mixes', to='botany.plantsubstrate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substrate_mixes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Substrate Mix',
                'verbose_name_plural': 'Substrate Mixes',
            },
        ),
        migrations.AddField(
            model_name='userplant',
            name='substrate_mix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_plants', to='botany.substratemix'),
        ),
    ]
