# Generated by Django 5.1 on 2024-10-20 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0013_plantsubstrate_substratemix_userplant_substrate_mix'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userplant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userplant',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='userplant',
            name='translation_key',
        ),
    ]
