# Generated by Django 5.1 on 2024-10-03 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0013_remove_userboxpage_page_ptr'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='inventory.inventoryboxpage'),
        ),
        migrations.DeleteModel(
            name='UserBoxPage',
        ),
    ]
