# Generated by Django 5.1 on 2024-10-06 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0014_alter_plant_box_delete_userboxpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='date',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='quantity',
        ),
    ]
