# Generated by Django 5.1 on 2024-10-20 16:56

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_baseimage_options'),
        ('botany', '0015_remove_userplant_substrate_mix_userplant_substrate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplant',
            name='notes',
        ),
        migrations.AddField(
            model_name='userplant',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.baseimage'),
        ),
        migrations.CreateModel(
            name='PlantNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('content', wagtail.fields.RichTextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plant', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='botany.userplant')),
            ],
            options={
                'verbose_name': 'Plant Note',
                'verbose_name_plural': 'Plant Notes',
            },
        ),
        migrations.DeleteModel(
            name='UserPlantGalleryImage',
        ),
    ]
